spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexum_name
    username: root
    password: yadav@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true